export interface Lead {
  id: string
  rank: number
  score: number
  name: string
  title: string
  company: string
  personalLocation: string
  hqLocation: string
  email: string
  phone: string
  linkedin: string
  fundingStage: "Seed" | "Series A" | "Series B" | "Series C" | "Public"
  lastPublication: string
  publicationTitle: string
  techStack: string[]
  recentActivity: string[]
  scoreBreakdown: {
    roleFit: number
    companyIntent: number
    technographic: number
    location: number
    scientificIntent: number
    engagement: number
  }
  isWatched: boolean
  status: "new" | "contacted" | "qualified" | "converted"
}

export const sampleLeads: Lead[] = [
  {
    id: "1",
    rank: 1,
    score: 96,
    name: "Dr. Sarah Chen",
    title: "VP of Preclinical Safety",
    company: "Moderna Therapeutics",
    personalLocation: "Cambridge, MA",
    hqLocation: "Cambridge, MA",
    email: "s.chen@modernatx.com",
    phone: "+1 617-714-6500",
    linkedin: "linkedin.com/in/sarahchen-tox",
    fundingStage: "Public",
    lastPublication: "2025-01-15",
    publicationTitle: "Novel 3D Hepatic Models for Drug-Induced Liver Injury Assessment in mRNA Therapeutics",
    techStack: ["3D Models", "NAMs", "Organoids", "iPSC"],
    recentActivity: ["Keynote Speaker at BIO 2024", "Published in Nature Hepatology", "Hiring 3 toxicologists"],
    scoreBreakdown: {
      roleFit: 30,
      companyIntent: 20,
      technographic: 15,
      location: 10,
      scientificIntent: 40,
      engagement: 10,
    },
    isWatched: true,
    status: "new",
  },
  {
    id: "2",
    rank: 2,
    score: 94,
    name: "Dr. Marcus Weber",
    title: "Global Head of Toxicology",
    company: "Novartis AG",
    personalLocation: "Basel, Switzerland",
    hqLocation: "Basel, Switzerland",
    email: "marcus.weber@novartis.com",
    phone: "+41 61 324 1111",
    linkedin: "linkedin.com/in/marcusweber-phd",
    fundingStage: "Public",
    lastPublication: "2024-12-22",
    publicationTitle: "In-Vitro Alternatives for Hepatotoxicity Screening in Early Drug Discovery",
    techStack: ["In-Vitro", "High-Throughput Screening", "NAMs", "AI/ML"],
    recentActivity: ["SOT 2024 Conference Chair", "Announced $50M NAMs initiative", "LinkedIn thought leadership"],
    scoreBreakdown: {
      roleFit: 30,
      companyIntent: 20,
      technographic: 14,
      location: 8,
      scientificIntent: 38,
      engagement: 10,
    },
    isWatched: true,
    status: "new",
  },
  {
    id: "3",
    rank: 3,
    score: 92,
    name: "Dr. Emily Thompson",
    title: "Head of Safety Assessment",
    company: "Genentech",
    personalLocation: "South San Francisco, CA",
    hqLocation: "South San Francisco, CA",
    email: "thompson.emily@gene.com",
    phone: "+1 650-225-1000",
    linkedin: "linkedin.com/in/emilythompson-safety",
    fundingStage: "Public",
    lastPublication: "2024-11-08",
    publicationTitle: "Predictive Hepatotoxicity Models Using Human iPSC-Derived Hepatocytes",
    techStack: ["iPSC", "3D Models", "NAMs", "Organoids"],
    recentActivity: ["Published in Cell Stem Cell", "Podcast interview on NAMs adoption"],
    scoreBreakdown: {
      roleFit: 28,
      companyIntent: 18,
      technographic: 15,
      location: 10,
      scientificIntent: 36,
      engagement: 9,
    },
    isWatched: true,
    status: "contacted",
  },
  {
    id: "4",
    rank: 4,
    score: 90,
    name: "Dr. James O'Brien",
    title: "Senior Director, Drug Safety Sciences",
    company: "AstraZeneca",
    personalLocation: "Cambridge, UK",
    hqLocation: "Cambridge, UK",
    email: "james.obrien@astrazeneca.com",
    phone: "+44 20 3749 5000",
    linkedin: "linkedin.com/in/jamesobrien-drugsafety",
    fundingStage: "Public",
    lastPublication: "2024-12-01",
    publicationTitle: "Advancing New Approach Methodologies in Regulatory Toxicology",
    techStack: ["NAMs", "QSAR", "Read-Across", "AI/ML"],
    recentActivity: ["EMA Advisory Committee Member", "Webinar Host: Future of Tox Testing"],
    scoreBreakdown: {
      roleFit: 28,
      companyIntent: 18,
      technographic: 14,
      location: 9,
      scientificIntent: 34,
      engagement: 10,
    },
    isWatched: false,
    status: "new",
  },
  {
    id: "5",
    rank: 5,
    score: 88,
    name: "Dr. Lisa Nakamura",
    title: "VP Toxicology & DMPK",
    company: "Gilead Sciences",
    personalLocation: "Foster City, CA",
    hqLocation: "Foster City, CA",
    email: "lisa.nakamura@gilead.com",
    phone: "+1 650-574-3000",
    linkedin: "linkedin.com/in/lisanakamura-tox",
    fundingStage: "Public",
    lastPublication: "2024-10-15",
    publicationTitle: "Integration of 3D Liver Models in Antiviral Drug Development Pipelines",
    techStack: ["3D Models", "Microfluidics", "NAMs"],
    recentActivity: ["Speaking at AASLD 2024", "Published DILI guidelines"],
    scoreBreakdown: {
      roleFit: 29,
      companyIntent: 16,
      technographic: 14,
      location: 10,
      scientificIntent: 32,
      engagement: 8,
    },
    isWatched: true,
    status: "new",
  },
  {
    id: "6",
    rank: 6,
    score: 86,
    name: "Dr. Robert Andersson",
    title: "Director of Hepatotoxicity Research",
    company: "AbbVie",
    personalLocation: "North Chicago, IL",
    hqLocation: "North Chicago, IL",
    email: "robert.andersson@abbvie.com",
    phone: "+1 847-932-7900",
    linkedin: "linkedin.com/in/robertandersson-hepatox",
    fundingStage: "Public",
    lastPublication: "2024-10-30",
    publicationTitle: "Mechanistic Biomarkers for Drug-Induced Hepatotoxicity in Immunology",
    techStack: ["Biomarkers", "In-Vitro", "3D Models"],
    recentActivity: ["LinkedIn post on DILI research", "Hiring senior toxicologist"],
    scoreBreakdown: {
      roleFit: 26,
      companyIntent: 19,
      technographic: 12,
      location: 8,
      scientificIntent: 30,
      engagement: 7,
    },
    isWatched: false,
    status: "new",
  },
  {
    id: "7",
    rank: 7,
    score: 85,
    name: "Dr. Priya Sharma",
    title: "Head of Preclinical Development",
    company: "BioNTech SE",
    personalLocation: "Mainz, Germany",
    hqLocation: "Mainz, Germany",
    email: "priya.sharma@biontech.de",
    phone: "+49 6131 9084 0",
    linkedin: "linkedin.com/in/priyasharma-preclin",
    fundingStage: "Public",
    lastPublication: "2024-09-20",
    publicationTitle: "Safety Assessment Strategies for mRNA-Based Therapeutics",
    techStack: ["NAMs", "In-Vitro", "Organoids"],
    recentActivity: ["Conference keynote", "Media interview on mRNA safety"],
    scoreBreakdown: {
      roleFit: 26,
      companyIntent: 17,
      technographic: 13,
      location: 8,
      scientificIntent: 32,
      engagement: 8,
    },
    isWatched: false,
    status: "qualified",
  },
  {
    id: "8",
    rank: 8,
    score: 83,
    name: "Dr. Michelle Rodriguez",
    title: "Associate Director, Safety Sciences",
    company: "Vertex Pharmaceuticals",
    personalLocation: "Boston, MA",
    hqLocation: "Boston, MA",
    email: "mrodriguez@vrtx.com",
    phone: "+1 617-341-6100",
    linkedin: "linkedin.com/in/michellerodriguez-safety",
    fundingStage: "Public",
    lastPublication: "2024-08-20",
    publicationTitle: "Comparative Analysis of 2D vs 3D Hepatocyte Models for Gene Therapy Safety",
    techStack: ["3D Models", "iPSC"],
    recentActivity: ["Job change announcement", "NAMs working group member"],
    scoreBreakdown: {
      roleFit: 24,
      companyIntent: 17,
      technographic: 13,
      location: 10,
      scientificIntent: 28,
      engagement: 7,
    },
    isWatched: false,
    status: "new",
  },
  {
    id: "9",
    rank: 9,
    score: 81,
    name: "Dr. Thomas Mueller",
    title: "VP Nonclinical Development",
    company: "Roche Pharmaceuticals",
    personalLocation: "Basel, Switzerland",
    hqLocation: "Basel, Switzerland",
    email: "thomas.mueller@roche.com",
    phone: "+41 61 688 1111",
    linkedin: "linkedin.com/in/thomasmueller-preclinical",
    fundingStage: "Public",
    lastPublication: "2024-07-12",
    publicationTitle: "Regulatory Acceptance of Alternative Toxicity Methods in Europe",
    techStack: ["NAMs", "QSAR", "Read-Across", "High-Throughput Screening"],
    recentActivity: ["ICH Expert Working Group", "Basel BioTech Summit speaker"],
    scoreBreakdown: {
      roleFit: 26,
      companyIntent: 14,
      technographic: 15,
      location: 8,
      scientificIntent: 26,
      engagement: 7,
    },
    isWatched: false,
    status: "new",
  },
  {
    id: "10",
    rank: 10,
    score: 79,
    name: "Dr. Jennifer Park",
    title: "Director of Toxicology",
    company: "Seagen (Pfizer)",
    personalLocation: "Bothell, WA",
    hqLocation: "Seattle, WA",
    email: "jpark@seagen.com",
    phone: "+1 425-527-4000",
    linkedin: "linkedin.com/in/jenniferpark-tox",
    fundingStage: "Public",
    lastPublication: "2024-11-05",
    publicationTitle: "Early Detection of Hepatotoxicity in Antibody-Drug Conjugates",
    techStack: ["In-Vitro", "Biomarkers", "3D Models"],
    recentActivity: ["Hiring announcement", "ADC safety consortium member"],
    scoreBreakdown: {
      roleFit: 28,
      companyIntent: 15,
      technographic: 11,
      location: 8,
      scientificIntent: 24,
      engagement: 6,
    },
    isWatched: false,
    status: "new",
  },
  {
    id: "11",
    rank: 11,
    score: 77,
    name: "Dr. David Kim",
    title: "Senior Scientist, Computational Toxicology",
    company: "Recursion Pharmaceuticals",
    personalLocation: "Salt Lake City, UT",
    hqLocation: "Salt Lake City, UT",
    email: "dkim@recursion.com",
    phone: "+1 385-498-0600",
    linkedin: "linkedin.com/in/davidkim-toxicology",
    fundingStage: "Public",
    lastPublication: "2024-12-18",
    publicationTitle: "Machine Learning Approaches to Hepatotoxicity Prediction at Scale",
    techStack: ["AI/ML", "QSAR", "High-Throughput Screening"],
    recentActivity: ["Published in Nature Machine Intelligence", "TechCrunch interview"],
    scoreBreakdown: {
      roleFit: 20,
      companyIntent: 18,
      technographic: 15,
      location: 6,
      scientificIntent: 26,
      engagement: 6,
    },
    isWatched: false,
    status: "contacted",
  },
  {
    id: "12",
    rank: 12,
    score: 75,
    name: "Dr. Anna Petrov",
    title: "VP Drug Safety",
    company: "Regeneron Pharmaceuticals",
    personalLocation: "Tarrytown, NY",
    hqLocation: "Tarrytown, NY",
    email: "anna.petrov@regeneron.com",
    phone: "+1 914-847-7000",
    linkedin: "linkedin.com/in/annapetrov-safety",
    fundingStage: "Public",
    lastPublication: "2024-04-22",
    publicationTitle: "Risk Assessment Strategies for Novel Antibody Modalities",
    techStack: ["In-Vitro", "Biomarkers"],
    recentActivity: ["Panel moderator at DIA", "Regulatory submission success"],
    scoreBreakdown: {
      roleFit: 26,
      companyIntent: 12,
      technographic: 10,
      location: 8,
      scientificIntent: 22,
      engagement: 8,
    },
    isWatched: false,
    status: "new",
  },
  {
    id: "13",
    rank: 13,
    score: 73,
    name: "Dr. Christopher Lee",
    title: "Associate Director, Nonclinical Safety",
    company: "Biogen",
    personalLocation: "Cambridge, MA",
    hqLocation: "Cambridge, MA",
    email: "christopher.lee@biogen.com",
    phone: "+1 617-679-2000",
    linkedin: "linkedin.com/in/christopherlee-nonclinical",
    fundingStage: "Public",
    lastPublication: "2024-06-28",
    publicationTitle: "Translational Safety Biomarkers in Neurodegenerative Drug Development",
    techStack: ["Biomarkers", "In-Vitro", "NAMs"],
    recentActivity: ["LinkedIn engagement", "Published review article"],
    scoreBreakdown: {
      roleFit: 22,
      companyIntent: 16,
      technographic: 11,
      location: 10,
      scientificIntent: 20,
      engagement: 5,
    },
    isWatched: false,
    status: "new",
  },
  {
    id: "14",
    rank: 14,
    score: 71,
    name: "Dr. Sophie Laurent",
    title: "Head of Toxicology",
    company: "Sanofi",
    personalLocation: "Paris, France",
    hqLocation: "Paris, France",
    email: "sophie.laurent@sanofi.com",
    phone: "+33 1 53 77 40 00",
    linkedin: "linkedin.com/in/sophielaurent-tox",
    fundingStage: "Public",
    lastPublication: "2024-09-15",
    publicationTitle: "European Perspectives on Alternative Testing Methods for Vaccines",
    techStack: ["In-Vitro", "NAMs", "3D Models"],
    recentActivity: ["EFPIA working group chair", "Company R&D day presenter"],
    scoreBreakdown: {
      roleFit: 26,
      companyIntent: 14,
      technographic: 12,
      location: 6,
      scientificIntent: 18,
      engagement: 6,
    },
    isWatched: false,
    status: "new",
  },
  {
    id: "15",
    rank: 15,
    score: 69,
    name: "Dr. Michael Santos",
    title: "Director of Safety Assessment",
    company: "Bluebird Bio",
    personalLocation: "Somerville, MA",
    hqLocation: "Somerville, MA",
    email: "msantos@bluebirdbio.com",
    phone: "+1 339-499-9300",
    linkedin: "linkedin.com/in/michaelsantos-safety",
    fundingStage: "Public",
    lastPublication: "2024-05-10",
    publicationTitle: "Challenges in Preclinical Safety Testing for Gene Therapies",
    techStack: ["In-Vitro", "Biomarkers"],
    recentActivity: ["Gene therapy consortium member", "Profile update"],
    scoreBreakdown: {
      roleFit: 24,
      companyIntent: 14,
      technographic: 8,
      location: 10,
      scientificIntent: 16,
      engagement: 4,
    },
    isWatched: false,
    status: "new",
  },
  {
    id: "16",
    rank: 16,
    score: 67,
    name: "Dr. Rachel Green",
    title: "Senior Director, Preclinical Safety",
    company: "Intellia Therapeutics",
    personalLocation: "Cambridge, MA",
    hqLocation: "Cambridge, MA",
    email: "rgreen@intelliatx.com",
    phone: "+1 857-285-6200",
    linkedin: "linkedin.com/in/rachelgreen-toxicologist",
    fundingStage: "Public",
    lastPublication: "2024-03-20",
    publicationTitle: "Safety Profiling of CRISPR-Based Gene Editing Therapies",
    techStack: ["In-Vitro", "Biomarkers", "NAMs"],
    recentActivity: ["CRISPR safety symposium organizer", "Job promotion"],
    scoreBreakdown: {
      roleFit: 22,
      companyIntent: 16,
      technographic: 10,
      location: 10,
      scientificIntent: 14,
      engagement: 5,
    },
    isWatched: false,
    status: "contacted",
  },
  {
    id: "17",
    rank: 17,
    score: 65,
    name: "Dr. Andrew Walsh",
    title: "Principal Scientist, DMPK & Toxicology",
    company: "Jazz Pharmaceuticals",
    personalLocation: "Dublin, Ireland",
    hqLocation: "Dublin, Ireland",
    email: "awalsh@jazzpharma.com",
    phone: "+353 1 634 3200",
    linkedin: "linkedin.com/in/andrewwalsh-dmpk",
    fundingStage: "Public",
    lastPublication: "2024-08-05",
    publicationTitle: "ADME Considerations in CNS Drug Hepatic Metabolism",
    techStack: ["In-Vitro", "Biomarkers"],
    recentActivity: ["Conference attendance", "Department expansion"],
    scoreBreakdown: {
      roleFit: 20,
      companyIntent: 14,
      technographic: 8,
      location: 8,
      scientificIntent: 16,
      engagement: 6,
    },
    isWatched: false,
    status: "new",
  },
  {
    id: "18",
    rank: 18,
    score: 63,
    name: "Dr. Karen Mitchell",
    title: "VP Regulatory Toxicology",
    company: "Amgen",
    personalLocation: "Thousand Oaks, CA",
    hqLocation: "Thousand Oaks, CA",
    email: "kmitchell@amgen.com",
    phone: "+1 805-447-1000",
    linkedin: "linkedin.com/in/karenmitchell-regtox",
    fundingStage: "Public",
    lastPublication: "2024-06-12",
    publicationTitle: "Regulatory Strategy for Biosimilar Safety Programs",
    techStack: ["Traditional", "Biomarkers"],
    recentActivity: ["FDA pre-IND meeting success", "Team expansion"],
    scoreBreakdown: {
      roleFit: 24,
      companyIntent: 10,
      technographic: 6,
      location: 8,
      scientificIntent: 14,
      engagement: 6,
    },
    isWatched: false,
    status: "new",
  },
  {
    id: "19",
    rank: 19,
    score: 61,
    name: "Dr. Richard Foster",
    title: "Director, Early Development Safety",
    company: "Takeda Pharmaceuticals",
    personalLocation: "Cambridge, MA",
    hqLocation: "Cambridge, MA",
    email: "richard.foster@takeda.com",
    phone: "+1 617-349-0200",
    linkedin: "linkedin.com/in/richardfoster-tox",
    fundingStage: "Public",
    lastPublication: "2024-04-18",
    publicationTitle: "Post-Market Safety Surveillance for Rare Disease Therapies",
    techStack: ["Traditional", "Biomarkers"],
    recentActivity: ["Profile view", "Rare disease conference attendee"],
    scoreBreakdown: {
      roleFit: 22,
      companyIntent: 12,
      technographic: 6,
      location: 10,
      scientificIntent: 12,
      engagement: 4,
    },
    isWatched: false,
    status: "new",
  },
  {
    id: "20",
    rank: 20,
    score: 59,
    name: "Dr. Laura Martinez",
    title: "Senior Scientist, Toxicology",
    company: "Beam Therapeutics",
    personalLocation: "Cambridge, MA",
    hqLocation: "Cambridge, MA",
    email: "lmartinez@beamtx.com",
    phone: "+1 857-327-8775",
    linkedin: "linkedin.com/in/lauramartinez-research",
    fundingStage: "Public",
    lastPublication: "2024-02-25",
    publicationTitle: "Hepatocyte Culture Optimization for Base Editing Therapeutics",
    techStack: ["In-Vitro", "3D Models"],
    recentActivity: ["ASH conference poster", "LinkedIn article"],
    scoreBreakdown: {
      roleFit: 18,
      companyIntent: 14,
      technographic: 10,
      location: 10,
      scientificIntent: 10,
      engagement: 4,
    },
    isWatched: false,
    status: "new",
  },
  {
    id: "21",
    rank: 21,
    score: 57,
    name: "Dr. Kevin Young",
    title: "Associate Director, Safety Sciences",
    company: "Alnylam Pharmaceuticals",
    personalLocation: "Cambridge, MA",
    hqLocation: "Cambridge, MA",
    email: "kyoung@alnylam.com",
    phone: "+1 617-551-8200",
    linkedin: "linkedin.com/in/kevinyoung-safety",
    fundingStage: "Public",
    lastPublication: "2024-01-10",
    publicationTitle: "Liver Safety Monitoring for RNAi Therapeutics",
    techStack: ["Biomarkers", "In-Vitro"],
    recentActivity: ["Profile update", "Team hiring"],
    scoreBreakdown: {
      roleFit: 20,
      companyIntent: 12,
      technographic: 8,
      location: 10,
      scientificIntent: 10,
      engagement: 4,
    },
    isWatched: false,
    status: "new",
  },
  {
    id: "22",
    rank: 22,
    score: 55,
    name: "Dr. Patricia Adams",
    title: "Director, Nonclinical Development",
    company: "CRISPR Therapeutics",
    personalLocation: "Cambridge, MA",
    hqLocation: "Zug, Switzerland",
    email: "padams@crisprtx.com",
    phone: "+1 617-315-4600",
    linkedin: "linkedin.com/in/patriciaadams-nonclin",
    fundingStage: "Public",
    lastPublication: "2024-11-30",
    publicationTitle: "Nonclinical Safety Strategies for In Vivo Gene Editing",
    techStack: ["In-Vitro", "Biomarkers"],
    recentActivity: ["ASGCT presenter", "LinkedIn engagement"],
    scoreBreakdown: {
      roleFit: 22,
      companyIntent: 10,
      technographic: 8,
      location: 10,
      scientificIntent: 8,
      engagement: 4,
    },
    isWatched: false,
    status: "new",
  },
  {
    id: "23",
    rank: 23,
    score: 53,
    name: "Dr. Steven Brown",
    title: "Head of Investigative Toxicology",
    company: "Bristol Myers Squibb",
    personalLocation: "Princeton, NJ",
    hqLocation: "Princeton, NJ",
    email: "steven.brown@bms.com",
    phone: "+1 609-252-4000",
    linkedin: "linkedin.com/in/stevenbrown-invtox",
    fundingStage: "Public",
    lastPublication: "2024-09-15",
    publicationTitle: "Mechanistic Toxicology in Oncology Drug Development",
    techStack: ["Traditional", "Biomarkers", "In-Vitro"],
    recentActivity: ["AACR meeting attendee", "None recent"],
    scoreBreakdown: {
      roleFit: 20,
      companyIntent: 10,
      technographic: 8,
      location: 6,
      scientificIntent: 8,
      engagement: 3,
    },
    isWatched: false,
    status: "new",
  },
  {
    id: "24",
    rank: 24,
    score: 82,
    name: "Dr. Yuki Tanaka",
    title: "VP Translational Safety",
    company: "Daiichi Sankyo",
    personalLocation: "Tokyo, Japan",
    hqLocation: "Tokyo, Japan",
    email: "ytanaka@daiichisankyo.co.jp",
    phone: "+81 3 6225 1111",
    linkedin: "linkedin.com/in/yukitanaka-transafety",
    fundingStage: "Public",
    lastPublication: "2024-11-25",
    publicationTitle: "ADC Hepatotoxicity Mechanisms and Mitigation Strategies",
    techStack: ["3D Models", "NAMs", "Biomarkers", "Microfluidics"],
    recentActivity: ["JSOT conference organizer", "ADC consortium leader"],
    scoreBreakdown: {
      roleFit: 28,
      companyIntent: 18,
      technographic: 14,
      location: 6,
      scientificIntent: 30,
      engagement: 8,
    },
    isWatched: true,
    status: "new",
  },
  {
    id: "25",
    rank: 25,
    score: 80,
    name: "Dr. Elena Volkov",
    title: "Senior Director, Drug Safety",
    company: "Incyte Corporation",
    personalLocation: "Wilmington, DE",
    hqLocation: "Wilmington, DE",
    email: "evolkov@incyte.com",
    phone: "+1 302-498-6700",
    linkedin: "linkedin.com/in/elenavolkov-drugsafety",
    fundingStage: "Public",
    lastPublication: "2024-10-10",
    publicationTitle: "Hepatic Safety Assessment of JAK Inhibitors",
    techStack: ["In-Vitro", "NAMs", "3D Models"],
    recentActivity: ["ACR presenter", "Published in Hepatology"],
    scoreBreakdown: {
      roleFit: 26,
      companyIntent: 17,
      technographic: 12,
      location: 6,
      scientificIntent: 28,
      engagement: 7,
    },
    isWatched: false,
    status: "qualified",
  },
  {
    id: "26",
    rank: 26,
    score: 78,
    name: "Dr. Hans Bergmann",
    title: "Head of Early Safety Assessment",
    company: "Boehringer Ingelheim",
    personalLocation: "Ingelheim, Germany",
    hqLocation: "Ingelheim, Germany",
    email: "hans.bergmann@boehringer-ingelheim.com",
    phone: "+49 6132 77 0",
    linkedin: "linkedin.com/in/hansbergmann-earlysafety",
    fundingStage: "Public",
    lastPublication: "2024-08-18",
    publicationTitle: "Organ-on-Chip Applications in Respiratory Drug Safety",
    techStack: ["Microfluidics", "NAMs", "Organoids"],
    recentActivity: ["EUROTOX speaker", "Organ-on-chip initiative lead"],
    scoreBreakdown: {
      roleFit: 24,
      companyIntent: 18,
      technographic: 14,
      location: 7,
      scientificIntent: 24,
      engagement: 7,
    },
    isWatched: false,
    status: "new",
  },
  {
    id: "27",
    rank: 27,
    score: 76,
    name: "Dr. Mei Lin Chang",
    title: "Director of Hepatic Safety",
    company: "Exelixis",
    personalLocation: "Alameda, CA",
    hqLocation: "Alameda, CA",
    email: "mchang@exelixis.com",
    phone: "+1 650-837-7000",
    linkedin: "linkedin.com/in/meilinchang-hepatic",
    fundingStage: "Public",
    lastPublication: "2024-07-28",
    publicationTitle: "Tyrosine Kinase Inhibitor Hepatotoxicity: Predictive Biomarkers",
    techStack: ["Biomarkers", "In-Vitro", "NAMs"],
    recentActivity: ["ASCO poster presentation", "Biomarker discovery grant"],
    scoreBreakdown: {
      roleFit: 26,
      companyIntent: 15,
      technographic: 11,
      location: 8,
      scientificIntent: 22,
      engagement: 6,
    },
    isWatched: false,
    status: "new",
  },
  {
    id: "28",
    rank: 28,
    score: 74,
    name: "Dr. Benjamin Clarke",
    title: "VP Preclinical Sciences",
    company: "Horizon Therapeutics",
    personalLocation: "Dublin, Ireland",
    hqLocation: "Dublin, Ireland",
    email: "bclarke@horizontherapeutics.com",
    phone: "+353 1 699 1900",
    linkedin: "linkedin.com/in/benjaminclarke-preclin",
    fundingStage: "Public",
    lastPublication: "2024-06-05",
    publicationTitle: "Safety Evaluation of Rare Disease Therapeutics",
    techStack: ["Traditional", "Biomarkers", "In-Vitro"],
    recentActivity: ["Rare disease advocate", "Company acquisition news"],
    scoreBreakdown: {
      roleFit: 24,
      companyIntent: 14,
      technographic: 9,
      location: 8,
      scientificIntent: 20,
      engagement: 6,
    },
    isWatched: false,
    status: "new",
  },
  {
    id: "29",
    rank: 29,
    score: 72,
    name: "Dr. Natalie Fischer",
    title: "Associate Director, Toxicology",
    company: "Argenx",
    personalLocation: "Ghent, Belgium",
    hqLocation: "Ghent, Belgium",
    email: "nfischer@argenx.com",
    phone: "+32 9 262 00 00",
    linkedin: "linkedin.com/in/nataliefischer-tox",
    fundingStage: "Public",
    lastPublication: "2024-05-20",
    publicationTitle: "FcRn Antagonist Safety: Lessons from Efgartigimod Development",
    techStack: ["In-Vitro", "Biomarkers"],
    recentActivity: ["EULAR presenter", "Autoimmune safety review author"],
    scoreBreakdown: {
      roleFit: 22,
      companyIntent: 16,
      technographic: 8,
      location: 6,
      scientificIntent: 20,
      engagement: 6,
    },
    isWatched: false,
    status: "new",
  },
  {
    id: "30",
    rank: 30,
    score: 70,
    name: "Dr. Carlos Mendez",
    title: "Director of Drug Metabolism & Toxicology",
    company: "Arcus Biosciences",
    personalLocation: "Hayward, CA",
    hqLocation: "Hayward, CA",
    email: "cmendez@arcusbio.com",
    phone: "+1 510-694-6200",
    linkedin: "linkedin.com/in/carlosmendez-dmtox",
    fundingStage: "Public",
    lastPublication: "2024-04-15",
    publicationTitle: "Immuno-Oncology Combination Therapy Safety Assessment",
    techStack: ["In-Vitro", "NAMs"],
    recentActivity: ["SITC meeting attendee", "IO safety publication"],
    scoreBreakdown: {
      roleFit: 24,
      companyIntent: 14,
      technographic: 10,
      location: 8,
      scientificIntent: 16,
      engagement: 5,
    },
    isWatched: false,
    status: "contacted",
  },
  {
    id: "31",
    rank: 31,
    score: 68,
    name: "Dr. Alexandra Stone",
    title: "Senior Director, Safety Assessment",
    company: "Ultragenyx Pharmaceutical",
    personalLocation: "Novato, CA",
    hqLocation: "Novato, CA",
    email: "astone@ultragenyx.com",
    phone: "+1 415-483-8800",
    linkedin: "linkedin.com/in/alexandrastone-safety",
    fundingStage: "Public",
    lastPublication: "2024-03-12",
    publicationTitle: "Gene Therapy Safety in Pediatric Rare Diseases",
    techStack: ["Traditional", "In-Vitro", "Biomarkers"],
    recentActivity: ["Rare disease day advocate", "FDA advisory committee member"],
    scoreBreakdown: {
      roleFit: 24,
      companyIntent: 12,
      technographic: 8,
      location: 8,
      scientificIntent: 14,
      engagement: 6,
    },
    isWatched: false,
    status: "new",
  },
  {
    id: "32",
    rank: 32,
    score: 66,
    name: "Dr. Jonathan Price",
    title: "Head of Toxicology Sciences",
    company: "Ipsen",
    personalLocation: "Paris, France",
    hqLocation: "Paris, France",
    email: "jonathan.price@ipsen.com",
    phone: "+33 1 58 33 50 00",
    linkedin: "linkedin.com/in/jonathanprice-toxsci",
    fundingStage: "Public",
    lastPublication: "2024-02-28",
    publicationTitle: "Safety Considerations for Peptide-Based Oncology Therapeutics",
    techStack: ["Traditional", "In-Vitro"],
    recentActivity: ["ESMO presenter", "Team restructuring"],
    scoreBreakdown: {
      roleFit: 24,
      companyIntent: 12,
      technographic: 6,
      location: 6,
      scientificIntent: 16,
      engagement: 5,
    },
    isWatched: false,
    status: "new",
  },
  {
    id: "33",
    rank: 33,
    score: 64,
    name: "Dr. Victoria Hansen",
    title: "Associate Director, Nonclinical Safety",
    company: "Alkermes",
    personalLocation: "Dublin, Ireland",
    hqLocation: "Dublin, Ireland",
    email: "vhansen@alkermes.com",
    phone: "+353 1 772 8000",
    linkedin: "linkedin.com/in/victoriahansen-nonclin",
    fundingStage: "Public",
    lastPublication: "2024-01-20",
    publicationTitle: "CNS Drug Safety: Blood-Brain Barrier Considerations",
    techStack: ["Traditional", "Biomarkers"],
    recentActivity: ["CNS summit attendee", "Blog post on BBB"],
    scoreBreakdown: {
      roleFit: 20,
      companyIntent: 14,
      technographic: 6,
      location: 8,
      scientificIntent: 14,
      engagement: 5,
    },
    isWatched: false,
    status: "new",
  },
  {
    id: "34",
    rank: 34,
    score: 87,
    name: "Dr. William Chen",
    title: "VP Safety Sciences",
    company: "Sarepta Therapeutics",
    personalLocation: "Cambridge, MA",
    hqLocation: "Cambridge, MA",
    email: "wchen@sarepta.com",
    phone: "+1 617-274-4000",
    linkedin: "linkedin.com/in/williamchen-safetysci",
    fundingStage: "Public",
    lastPublication: "2024-12-05",
    publicationTitle: "AAV Gene Therapy Hepatotoxicity: Mechanisms and Monitoring",
    techStack: ["3D Models", "NAMs", "Biomarkers", "iPSC"],
    recentActivity: ["Gene therapy safety consortium chair", "FDA meeting success"],
    scoreBreakdown: {
      roleFit: 28,
      companyIntent: 18,
      technographic: 14,
      location: 10,
      scientificIntent: 32,
      engagement: 9,
    },
    isWatched: true,
    status: "new",
  },
  {
    id: "35",
    rank: 35,
    score: 84,
    name: "Dr. Isabella Romano",
    title: "Global Head of Investigative Toxicology",
    company: "Merck KGaA",
    personalLocation: "Darmstadt, Germany",
    hqLocation: "Darmstadt, Germany",
    email: "isabella.romano@merckgroup.com",
    phone: "+49 6151 72 0",
    linkedin: "linkedin.com/in/isabellaromano-invtox",
    fundingStage: "Public",
    lastPublication: "2024-10-28",
    publicationTitle: "Predictive In Vitro Models for Hepatic Steatosis",
    techStack: ["3D Models", "NAMs", "High-Throughput Screening", "Organoids"],
    recentActivity: ["ESTIV organizer", "Published in Toxicological Sciences"],
    scoreBreakdown: {
      roleFit: 26,
      companyIntent: 18,
      technographic: 15,
      location: 7,
      scientificIntent: 30,
      engagement: 8,
    },
    isWatched: true,
    status: "qualified",
  },
  {
    id: "36",
    rank: 36,
    score: 62,
    name: "Dr. Daniel Morrison",
    title: "Director, Safety Pharmacology",
    company: "Neurocrine Biosciences",
    personalLocation: "San Diego, CA",
    hqLocation: "San Diego, CA",
    email: "dmorrison@neurocrine.com",
    phone: "+1 858-617-7600",
    linkedin: "linkedin.com/in/danielmorrison-safetypharm",
    fundingStage: "Public",
    lastPublication: "2024-07-05",
    publicationTitle: "CNS Safety Pharmacology: Current Challenges and Solutions",
    techStack: ["Traditional", "In-Vitro"],
    recentActivity: ["SPS meeting attendee", "LinkedIn post"],
    scoreBreakdown: {
      roleFit: 20,
      companyIntent: 14,
      technographic: 6,
      location: 8,
      scientificIntent: 14,
      engagement: 4,
    },
    isWatched: false,
    status: "new",
  },
  {
    id: "37",
    rank: 37,
    score: 60,
    name: "Dr. Nina Johansson",
    title: "Senior Director, Preclinical Development",
    company: "Orion Corporation",
    personalLocation: "Espoo, Finland",
    hqLocation: "Espoo, Finland",
    email: "nina.johansson@orion.fi",
    phone: "+358 10 4261",
    linkedin: "linkedin.com/in/ninajohansson-preclin",
    fundingStage: "Public",
    lastPublication: "2024-06-20",
    publicationTitle: "Nordic Approach to Animal-Free Testing in Drug Development",
    techStack: ["NAMs", "In-Vitro"],
    recentActivity: ["Nordic pharma summit speaker", "Sustainability initiative"],
    scoreBreakdown: {
      roleFit: 22,
      companyIntent: 12,
      technographic: 10,
      location: 5,
      scientificIntent: 12,
      engagement: 5,
    },
    isWatched: false,
    status: "new",
  },
  {
    id: "38",
    rank: 38,
    score: 58,
    name: "Dr. Gregory Wilson",
    title: "Associate Director, DMPK-Tox",
    company: "Agios Pharmaceuticals",
    personalLocation: "Cambridge, MA",
    hqLocation: "Cambridge, MA",
    email: "gwilson@agios.com",
    phone: "+1 617-649-8600",
    linkedin: "linkedin.com/in/gregorywilson-dmpktox",
    fundingStage: "Public",
    lastPublication: "2024-05-15",
    publicationTitle: "Metabolic Enzyme Inhibition and Hepatotoxicity Risk",
    techStack: ["In-Vitro", "Biomarkers"],
    recentActivity: ["ASH poster", "Profile update"],
    scoreBreakdown: {
      roleFit: 18,
      companyIntent: 14,
      technographic: 8,
      location: 10,
      scientificIntent: 10,
      engagement: 4,
    },
    isWatched: false,
    status: "new",
  },
  {
    id: "39",
    rank: 39,
    score: 56,
    name: "Dr. Elizabeth Turner",
    title: "Director of Drug Safety",
    company: "Deciphera Pharmaceuticals",
    personalLocation: "Waltham, MA",
    hqLocation: "Waltham, MA",
    email: "eturner@deciphera.com",
    phone: "+1 781-209-6400",
    linkedin: "linkedin.com/in/elizabethturner-drugsafety",
    fundingStage: "Public",
    lastPublication: "2024-04-08",
    publicationTitle: "Kinase Inhibitor Cardiotoxicity and Hepatotoxicity Monitoring",
    techStack: ["Traditional", "Biomarkers"],
    recentActivity: ["GIST symposium presenter", "Team expansion"],
    scoreBreakdown: {
      roleFit: 22,
      companyIntent: 10,
      technographic: 6,
      location: 10,
      scientificIntent: 10,
      engagement: 4,
    },
    isWatched: false,
    status: "new",
  },
  {
    id: "40",
    rank: 40,
    score: 54,
    name: "Dr. Mark Anderson",
    title: "Principal Toxicologist",
    company: "Y-mAbs Therapeutics",
    personalLocation: "New York, NY",
    hqLocation: "New York, NY",
    email: "manderson@ymabs.com",
    phone: "+1 646-885-8505",
    linkedin: "linkedin.com/in/markanderson-tox",
    fundingStage: "Public",
    lastPublication: "2024-03-01",
    publicationTitle: "Pediatric Oncology Drug Safety Considerations",
    techStack: ["Traditional", "In-Vitro"],
    recentActivity: ["Pediatric oncology safety review", "LinkedIn engagement"],
    scoreBreakdown: {
      roleFit: 18,
      companyIntent: 12,
      technographic: 6,
      location: 8,
      scientificIntent: 8,
      engagement: 4,
    },
    isWatched: false,
    status: "new",
  },
  {
    id: "41",
    rank: 41,
    score: 52,
    name: "Dr. Christine Baker",
    title: "Senior Toxicologist",
    company: "Karyopharm Therapeutics",
    personalLocation: "Newton, MA",
    hqLocation: "Newton, MA",
    email: "cbaker@karyopharm.com",
    phone: "+1 617-658-0600",
    linkedin: "linkedin.com/in/christinebaker-tox",
    fundingStage: "Public",
    lastPublication: "2024-02-10",
    publicationTitle: "Nuclear Export Inhibitor Safety Profile Analysis",
    techStack: ["Traditional"],
    recentActivity: ["Profile update", "Conference attendance"],
    scoreBreakdown: {
      roleFit: 16,
      companyIntent: 12,
      technographic: 4,
      location: 10,
      scientificIntent: 8,
      engagement: 3,
    },
    isWatched: false,
    status: "new",
  },
  {
    id: "42",
    rank: 42,
    score: 89,
    name: "Dr. Hiroshi Yamamoto",
    title: "Chief Scientific Officer",
    company: "PTC Therapeutics",
    personalLocation: "South Plainfield, NJ",
    hqLocation: "South Plainfield, NJ",
    email: "hyamamoto@ptcbio.com",
    phone: "+1 908-912-9256",
    linkedin: "linkedin.com/in/hiroshiyamamoto-cso",
    fundingStage: "Public",
    lastPublication: "2024-12-12",
    publicationTitle: "Gene Therapy Safety: From Bench to Bedside",
    techStack: ["3D Models", "NAMs", "iPSC", "Organoids", "AI/ML"],
    recentActivity: ["Gene therapy consortium board", "Nature Reviews article", "Hiring VP Safety"],
    scoreBreakdown: {
      roleFit: 30,
      companyIntent: 20,
      technographic: 15,
      location: 6,
      scientificIntent: 36,
      engagement: 9,
    },
    isWatched: true,
    status: "new",
  },
  {
    id: "43",
    rank: 43,
    score: 50,
    name: "Dr. Rebecca Hall",
    title: "Associate Director, Regulatory Toxicology",
    company: "Acceleron Pharma (Merck)",
    personalLocation: "Cambridge, MA",
    hqLocation: "Cambridge, MA",
    email: "rhall@acceleronpharma.com",
    phone: "+1 617-649-9200",
    linkedin: "linkedin.com/in/rebeccahall-regtox",
    fundingStage: "Public",
    lastPublication: "2024-01-05",
    publicationTitle: "TGF-beta Pathway Modulator Safety Assessment",
    techStack: ["Traditional"],
    recentActivity: ["Acquisition integration", "Profile update"],
    scoreBreakdown: {
      roleFit: 20,
      companyIntent: 8,
      technographic: 4,
      location: 10,
      scientificIntent: 6,
      engagement: 3,
    },
    isWatched: false,
    status: "new",
  },
  {
    id: "44",
    rank: 44,
    score: 48,
    name: "Dr. Timothy Roberts",
    title: "Toxicology Consultant",
    company: "Independent",
    personalLocation: "San Francisco, CA",
    hqLocation: "Remote",
    email: "tim.roberts@toxconsulting.com",
    phone: "+1 415-555-0189",
    linkedin: "linkedin.com/in/timothyroberts-toxconsult",
    fundingStage: "Seed",
    lastPublication: "2023-12-20",
    publicationTitle: "Regulatory Guidance for First-in-Human Studies",
    techStack: ["Traditional"],
    recentActivity: ["Blog post", "Consulting engagements"],
    scoreBreakdown: {
      roleFit: 18,
      companyIntent: 6,
      technographic: 2,
      location: 8,
      scientificIntent: 6,
      engagement: 5,
    },
    isWatched: false,
    status: "new",
  },
  {
    id: "45",
    rank: 45,
    score: 46,
    name: "Dr. Amanda Lewis",
    title: "Senior Scientist, Safety",
    company: "IGM Biosciences",
    personalLocation: "Mountain View, CA",
    hqLocation: "Mountain View, CA",
    email: "alewis@igmbio.com",
    phone: "+1 650-965-0200",
    linkedin: "linkedin.com/in/amandalewis-safety",
    fundingStage: "Public",
    lastPublication: "2023-11-15",
    publicationTitle: "IgM Antibody Safety Considerations",
    techStack: ["Traditional", "In-Vitro"],
    recentActivity: ["Team meeting", "Profile update"],
    scoreBreakdown: {
      roleFit: 14,
      companyIntent: 10,
      technographic: 6,
      location: 8,
      scientificIntent: 6,
      engagement: 3,
    },
    isWatched: false,
    status: "new",
  },
  {
    id: "46",
    rank: 46,
    score: 44,
    name: "Dr. Robert Kim",
    title: "Director, Early Development",
    company: "Praxis Precision Medicines",
    personalLocation: "Cambridge, MA",
    hqLocation: "Cambridge, MA",
    email: "rkim@praxismedicines.com",
    phone: "+1 617-300-8460",
    linkedin: "linkedin.com/in/robertkim-earlydev",
    fundingStage: "Public",
    lastPublication: "2023-10-25",
    publicationTitle: "CNS Ion Channel Modulator Safety Profiling",
    techStack: ["Traditional"],
    recentActivity: ["Conference attendance", "LinkedIn"],
    scoreBreakdown: {
      roleFit: 18,
      companyIntent: 8,
      technographic: 4,
      location: 10,
      scientificIntent: 4,
      engagement: 3,
    },
    isWatched: false,
    status: "new",
  },
  {
    id: "47",
    rank: 47,
    score: 42,
    name: "Dr. Jennifer Collins",
    title: "Senior Toxicologist",
    company: "Syndax Pharmaceuticals",
    personalLocation: "Waltham, MA",
    hqLocation: "Waltham, MA",
    email: "jcollins@syndax.com",
    phone: "+1 781-795-9419",
    linkedin: "linkedin.com/in/jennifercollins-tox",
    fundingStage: "Public",
    lastPublication: "2023-09-18",
    publicationTitle: "Epigenetic Modifier Safety in Oncology",
    techStack: ["Traditional"],
    recentActivity: ["ASH meeting", "None recent"],
    scoreBreakdown: {
      roleFit: 16,
      companyIntent: 8,
      technographic: 4,
      location: 10,
      scientificIntent: 4,
      engagement: 2,
    },
    isWatched: false,
    status: "new",
  },
  {
    id: "48",
    rank: 48,
    score: 40,
    name: "Dr. Matthew Davis",
    title: "Associate Toxicologist",
    company: "SpringWorks Therapeutics",
    personalLocation: "Stamford, CT",
    hqLocation: "Stamford, CT",
    email: "mdavis@springworkstx.com",
    phone: "+1 203-883-9490",
    linkedin: "linkedin.com/in/matthewdavis-tox",
    fundingStage: "Public",
    lastPublication: "2023-08-22",
    publicationTitle: "Targeted Protein Degradation Safety Considerations",
    techStack: ["Traditional"],
    recentActivity: ["Profile update", "None recent"],
    scoreBreakdown: {
      roleFit: 12,
      companyIntent: 10,
      technographic: 4,
      location: 6,
      scientificIntent: 4,
      engagement: 3,
    },
    isWatched: false,
    status: "new",
  },
  {
    id: "49",
    rank: 49,
    score: 38,
    name: "Dr. Sarah Mitchell",
    title: "Scientist II, Toxicology",
    company: "Karuna Therapeutics (BMS)",
    personalLocation: "Boston, MA",
    hqLocation: "Boston, MA",
    email: "smitchell@karunatx.com",
    phone: "+1 857-449-2244",
    linkedin: "linkedin.com/in/sarahmitchell-tox",
    fundingStage: "Public",
    lastPublication: "2023-07-10",
    publicationTitle: "Muscarinic Receptor Safety in Schizophrenia Treatment",
    techStack: ["Traditional"],
    recentActivity: ["Acquisition news", "None recent"],
    scoreBreakdown: {
      roleFit: 12,
      companyIntent: 8,
      technographic: 4,
      location: 10,
      scientificIntent: 4,
      engagement: 2,
    },
    isWatched: false,
    status: "new",
  },
  {
    id: "50",
    rank: 50,
    score: 36,
    name: "Dr. Andrew Thompson",
    title: "Research Scientist",
    company: "Relay Therapeutics",
    personalLocation: "Cambridge, MA",
    hqLocation: "Cambridge, MA",
    email: "athompson@relaytx.com",
    phone: "+1 617-370-8837",
    linkedin: "linkedin.com/in/andrewthompson-research",
    fundingStage: "Public",
    lastPublication: "2023-06-15",
    publicationTitle: "Motion-Based Drug Design and Safety Implications",
    techStack: ["AI/ML", "Traditional"],
    recentActivity: ["LinkedIn post", "None recent"],
    scoreBreakdown: {
      roleFit: 10,
      companyIntent: 8,
      technographic: 6,
      location: 10,
      scientificIntent: 2,
      engagement: 2,
    },
    isWatched: false,
    status: "new",
  },
  {
    id: "51",
    rank: 51,
    score: 91,
    name: "Dr. Catherine Zhou",
    title: "VP Translational Medicine & Safety",
    company: "Legend Biotech",
    personalLocation: "Somerset, NJ",
    hqLocation: "Somerset, NJ",
    email: "czhou@legendbiotech.com",
    phone: "+1 732-317-5050",
    linkedin: "linkedin.com/in/catherinezhou-transmed",
    fundingStage: "Public",
    lastPublication: "2024-12-20",
    publicationTitle: "CAR-T Cell Therapy Hepatotoxicity: Prevention and Management",
    techStack: ["3D Models", "NAMs", "iPSC", "Biomarkers"],
    recentActivity: ["ASH keynote speaker", "Cell therapy safety consortium founder", "Hiring 5 safety scientists"],
    scoreBreakdown: {
      roleFit: 30,
      companyIntent: 20,
      technographic: 14,
      location: 6,
      scientificIntent: 38,
      engagement: 9,
    },
    isWatched: true,
    status: "new",
  },
  {
    id: "52",
    rank: 52,
    score: 34,
    name: "Dr. Ryan Murphy",
    title: "Toxicology Specialist",
    company: "Bicycle Therapeutics",
    personalLocation: "Cambridge, UK",
    hqLocation: "Cambridge, UK",
    email: "rmurphy@bicycletherapeutics.com",
    phone: "+44 1223 261 503",
    linkedin: "linkedin.com/in/ryanmurphy-tox",
    fundingStage: "Public",
    lastPublication: "2023-05-20",
    publicationTitle: "Bicyclic Peptide Safety Assessment",
    techStack: ["Traditional"],
    recentActivity: ["Profile update", "None recent"],
    scoreBreakdown: {
      roleFit: 14,
      companyIntent: 6,
      technographic: 4,
      location: 6,
      scientificIntent: 2,
      engagement: 2,
    },
    isWatched: false,
    status: "new",
  },
  {
    id: "53",
    rank: 53,
    score: 32,
    name: "Dr. Lisa Wang",
    title: "Scientist, Safety Assessment",
    company: "Compass Pathways",
    personalLocation: "London, UK",
    hqLocation: "London, UK",
    email: "lwang@compasspathways.com",
    phone: "+44 20 7492 0400",
    linkedin: "linkedin.com/in/lisawang-safety",
    fundingStage: "Public",
    lastPublication: "2023-04-12",
    publicationTitle: "Psilocybin Therapy Safety Considerations",
    techStack: ["Traditional"],
    recentActivity: ["Mental health awareness", "None recent"],
    scoreBreakdown: {
      roleFit: 10,
      companyIntent: 6,
      technographic: 4,
      location: 6,
      scientificIntent: 4,
      engagement: 2,
    },
    isWatched: false,
    status: "new",
  },
  {
    id: "54",
    rank: 54,
    score: 30,
    name: "Dr. James Peterson",
    title: "Associate Director, Drug Safety",
    company: "Scholar Rock",
    personalLocation: "Cambridge, MA",
    hqLocation: "Cambridge, MA",
    email: "jpeterson@scholarrock.com",
    phone: "+1 617-766-6950",
    linkedin: "linkedin.com/in/jamespeterson-drugsafety",
    fundingStage: "Public",
    lastPublication: "2023-03-08",
    publicationTitle: "TGF-beta Modulator Hepatic Effects",
    techStack: ["Traditional"],
    recentActivity: ["None recent"],
    scoreBreakdown: {
      roleFit: 16,
      companyIntent: 4,
      technographic: 2,
      location: 10,
      scientificIntent: 0,
      engagement: 0,
    },
    isWatched: false,
    status: "new",
  },
  {
    id: "55",
    rank: 55,
    score: 28,
    name: "Dr. Michelle Chen",
    title: "Toxicologist",
    company: "Forma Therapeutics (Novo Nordisk)",
    personalLocation: "Watertown, MA",
    hqLocation: "Watertown, MA",
    email: "mchen@formatherapeutics.com",
    phone: "+1 617-245-0161",
    linkedin: "linkedin.com/in/michellechen-tox",
    fundingStage: "Public",
    lastPublication: "2023-02-15",
    publicationTitle: "Sickle Cell Disease Therapy Safety",
    techStack: ["Traditional"],
    recentActivity: ["Acquisition complete", "None recent"],
    scoreBreakdown: {
      roleFit: 14,
      companyIntent: 4,
      technographic: 2,
      location: 10,
      scientificIntent: 0,
      engagement: 0,
    },
    isWatched: false,
    status: "new",
  },
  {
    id: "56",
    rank: 56,
    score: 79,
    name: "Dr. Erik Lindqvist",
    title: "Head of Investigative Toxicology",
    company: "Sobi (Swedish Orphan Biovitrum)",
    personalLocation: "Stockholm, Sweden",
    hqLocation: "Stockholm, Sweden",
    email: "erik.lindqvist@sobi.com",
    phone: "+46 8 697 20 00",
    linkedin: "linkedin.com/in/eriklindqvist-invtox",
    fundingStage: "Public",
    lastPublication: "2024-09-30",
    publicationTitle: "Rare Blood Disorder Therapy Safety: A Comprehensive Review",
    techStack: ["NAMs", "3D Models", "In-Vitro", "Biomarkers"],
    recentActivity: ["EHA presenter", "Published in Blood", "Swedish pharma council member"],
    scoreBreakdown: {
      roleFit: 26,
      companyIntent: 16,
      technographic: 12,
      location: 6,
      scientificIntent: 26,
      engagement: 7,
    },
    isWatched: false,
    status: "qualified",
  },
  {
    id: "57",
    rank: 57,
    score: 26,
    name: "Dr. David Clark",
    title: "Senior Scientist",
    company: "Krystal Biotech",
    personalLocation: "Pittsburgh, PA",
    hqLocation: "Pittsburgh, PA",
    email: "dclark@krystalbio.com",
    phone: "+1 412-586-5830",
    linkedin: "linkedin.com/in/davidclark-scientist",
    fundingStage: "Public",
    lastPublication: "2023-01-20",
    publicationTitle: "Topical Gene Therapy Safety Assessment",
    techStack: ["Traditional"],
    recentActivity: ["None recent"],
    scoreBreakdown: {
      roleFit: 12,
      companyIntent: 4,
      technographic: 2,
      location: 4,
      scientificIntent: 2,
      engagement: 2,
    },
    isWatched: false,
    status: "new",
  },
  {
    id: "58",
    rank: 58,
    score: 24,
    name: "Dr. Nancy Taylor",
    title: "Research Associate",
    company: "Aprea Therapeutics",
    personalLocation: "Boston, MA",
    hqLocation: "Boston, MA",
    email: "ntaylor@aprea.com",
    phone: "+1 617-804-6040",
    linkedin: "linkedin.com/in/nancytaylor-research",
    fundingStage: "Public",
    lastPublication: "2022-12-10",
    publicationTitle: "p53 Reactivation Safety Studies",
    techStack: ["Traditional"],
    recentActivity: ["None recent"],
    scoreBreakdown: {
      roleFit: 8,
      companyIntent: 4,
      technographic: 2,
      location: 10,
      scientificIntent: 0,
      engagement: 0,
    },
    isWatched: false,
    status: "new",
  },
  {
    id: "59",
    rank: 59,
    score: 22,
    name: "Dr. Eric Johnson",
    title: "Toxicology Associate",
    company: "Replimune Group",
    personalLocation: "Woburn, MA",
    hqLocation: "Woburn, MA",
    email: "ejohnson@replimune.com",
    phone: "+1 781-222-9600",
    linkedin: "linkedin.com/in/ericjohnson-tox",
    fundingStage: "Public",
    lastPublication: "2022-11-05",
    publicationTitle: "Oncolytic Virus Safety Protocols",
    techStack: ["Traditional"],
    recentActivity: ["None recent"],
    scoreBreakdown: {
      roleFit: 10,
      companyIntent: 4,
      technographic: 2,
      location: 8,
      scientificIntent: 0,
      engagement: 0,
    },
    isWatched: false,
    status: "new",
  },
  {
    id: "60",
    rank: 60,
    score: 75,
    name: "Dr. Francesca De Luca",
    title: "Director of Preclinical Safety",
    company: "Chiesi Farmaceutici",
    personalLocation: "Parma, Italy",
    hqLocation: "Parma, Italy",
    email: "f.deluca@chiesi.com",
    phone: "+39 0521 2791",
    linkedin: "linkedin.com/in/francescadeluca-preclin",
    fundingStage: "Public",
    lastPublication: "2024-08-12",
    publicationTitle: "Respiratory Drug Safety Assessment Using Organ-on-Chip",
    techStack: ["NAMs", "Microfluidics", "3D Models"],
    recentActivity: ["ERS presenter", "Sustainability in pharma advocate"],
    scoreBreakdown: {
      roleFit: 24,
      companyIntent: 16,
      technographic: 12,
      location: 5,
      scientificIntent: 22,
      engagement: 6,
    },
    isWatched: false,
    status: "new",
  },
  {
    id: "61",
    rank: 61,
    score: 20,
    name: "Dr. Brian Wilson",
    title: "Lab Supervisor, Toxicology",
    company: "Turning Point Therapeutics (BMS)",
    personalLocation: "San Diego, CA",
    hqLocation: "San Diego, CA",
    email: "bwilson@tptherapeutics.com",
    phone: "+1 858-926-5251",
    linkedin: "linkedin.com/in/brianwilson-lab",
    fundingStage: "Public",
    lastPublication: "2022-10-18",
    publicationTitle: "Kinase Inhibitor Safety Screening Methods",
    techStack: ["Traditional"],
    recentActivity: ["None recent"],
    scoreBreakdown: {
      roleFit: 8,
      companyIntent: 4,
      technographic: 2,
      location: 6,
      scientificIntent: 0,
      engagement: 0,
    },
    isWatched: false,
    status: "new",
  },
  {
    id: "62",
    rank: 62,
    score: 85,
    name: "Dr. Aisha Rahman",
    title: "VP Global Drug Safety",
    company: "GSK (GlaxoSmithKline)",
    personalLocation: "London, UK",
    hqLocation: "London, UK",
    email: "aisha.rahman@gsk.com",
    phone: "+44 20 8047 5000",
    linkedin: "linkedin.com/in/aisharahman-globalsafety",
    fundingStage: "Public",
    lastPublication: "2024-11-08",
    publicationTitle: "AI-Powered Safety Assessment: GSK's Approach to Modern Toxicology",
    techStack: ["AI/ML", "NAMs", "3D Models", "High-Throughput Screening"],
    recentActivity: [
      "World Economic Forum panelist",
      "Nature Reviews Drug Discovery article",
      "NAMs investment announcement",
    ],
    scoreBreakdown: {
      roleFit: 28,
      companyIntent: 18,
      technographic: 15,
      location: 8,
      scientificIntent: 30,
      engagement: 8,
    },
    isWatched: true,
    status: "new",
  },
  {
    id: "63",
    rank: 63,
    score: 18,
    name: "Dr. Kelly Martin",
    title: "QA Manager, Tox Studies",
    company: "Aptinyx",
    personalLocation: "Evanston, IL",
    hqLocation: "Evanston, IL",
    email: "kmartin@aptinyx.com",
    phone: "+1 847-871-0377",
    linkedin: "linkedin.com/in/kellymartin-qa",
    fundingStage: "Public",
    lastPublication: "2022-09-25",
    publicationTitle: "GLP Compliance in Toxicology Studies",
    techStack: ["Traditional"],
    recentActivity: ["None recent"],
    scoreBreakdown: {
      roleFit: 6,
      companyIntent: 4,
      technographic: 2,
      location: 4,
      scientificIntent: 0,
      engagement: 2,
    },
    isWatched: false,
    status: "new",
  },
  {
    id: "64",
    rank: 64,
    score: 16,
    name: "Dr. Peter Nguyen",
    title: "Research Associate II",
    company: "G1 Therapeutics",
    personalLocation: "Research Triangle, NC",
    hqLocation: "Research Triangle, NC",
    email: "pnguyen@g1therapeutics.com",
    phone: "+1 919-213-9835",
    linkedin: "linkedin.com/in/peternguyen-research",
    fundingStage: "Public",
    lastPublication: "2022-08-15",
    publicationTitle: "CDK Inhibitor Bone Marrow Safety",
    techStack: ["Traditional"],
    recentActivity: ["None recent"],
    scoreBreakdown: {
      roleFit: 6,
      companyIntent: 4,
      technographic: 2,
      location: 4,
      scientificIntent: 0,
      engagement: 0,
    },
    isWatched: false,
    status: "new",
  },
  {
    id: "65",
    rank: 65,
    score: 14,
    name: "Dr. Susan Lee",
    title: "Junior Toxicologist",
    company: "Kinnate Biopharma",
    personalLocation: "San Diego, CA",
    hqLocation: "San Diego, CA",
    email: "slee@kinnatebio.com",
    phone: "+1 858-299-4699",
    linkedin: "linkedin.com/in/susanlee-jrtox",
    fundingStage: "Public",
    lastPublication: "2022-07-10",
    publicationTitle: "Basic Toxicology Methods Review",
    techStack: ["Traditional"],
    recentActivity: ["Career development post"],
    scoreBreakdown: {
      roleFit: 4,
      companyIntent: 4,
      technographic: 2,
      location: 6,
      scientificIntent: 0,
      engagement: 2,
    },
    isWatched: false,
    status: "new",
  },
]

export const fundingStageColors: Record<Lead["fundingStage"], string> = {
  Seed: "bg-slate-100 text-slate-700",
  "Series A": "bg-emerald-100 text-emerald-700",
  "Series B": "bg-blue-100 text-blue-700",
  "Series C": "bg-purple-100 text-purple-700",
  Public: "bg-amber-100 text-amber-700",
}

export const techStackColors: Record<string, string> = {
  "3D Models": "bg-blue-50 text-blue-600 border-blue-200",
  NAMs: "bg-emerald-50 text-emerald-600 border-emerald-200",
  Organoids: "bg-purple-50 text-purple-600 border-purple-200",
  "In-Vitro": "bg-teal-50 text-teal-600 border-teal-200",
  iPSC: "bg-pink-50 text-pink-600 border-pink-200",
  "High-Throughput Screening": "bg-orange-50 text-orange-600 border-orange-200",
  QSAR: "bg-indigo-50 text-indigo-600 border-indigo-200",
  Microfluidics: "bg-cyan-50 text-cyan-600 border-cyan-200",
  "AI/ML": "bg-violet-50 text-violet-600 border-violet-200",
  Biomarkers: "bg-rose-50 text-rose-600 border-rose-200",
  "Read-Across": "bg-lime-50 text-lime-600 border-lime-200",
  Traditional: "bg-gray-50 text-gray-600 border-gray-200",
}

export const statusColors: Record<Lead["status"], string> = {
  new: "bg-blue-100 text-blue-700",
  contacted: "bg-amber-100 text-amber-700",
  qualified: "bg-emerald-100 text-emerald-700",
  converted: "bg-purple-100 text-purple-700",
}

export const locations = [
  "All Locations",
  "Cambridge, MA",
  "Boston, MA",
  "San Francisco, CA",
  "South San Francisco, CA",
  "San Diego, CA",
  "New York, NY",
  "Basel, Switzerland",
  "Cambridge, UK",
  "London, UK",
  "Paris, France",
  "Dublin, Ireland",
  "Tokyo, Japan",
  "Germany",
  "Other US",
  "Other Europe",
  "Other",
]

export const jobTitles = [
  "All Titles",
  "VP",
  "Director",
  "Head of",
  "Senior Director",
  "Associate Director",
  "Principal",
  "Senior Scientist",
  "CSO",
]

export const fundingStages = ["All Stages", "Seed", "Series A", "Series B", "Series C", "Public"]
